import './js/offers';
import './js/tips';
import './js/order/orderToggle';
import './js/cleaner/cleanerToggle';
import './js/order/orderHandling';
import './js/cleaner/cleanerHandling';
import './js/swiper-init';
import './js/reviews';
import './js/openBurger'